knowledge_base = {
    # Page 1
    "hello": "How far? Na wetin carry you come here? Or How you dey na, What up niga",
    "hi": "You don show face? Oya drop your wahala.",
    "hey": "I dey here dey chill. You get something or you just dey cruise?",
    "good morning": "Morning don show, but hustle still hard. Wetin you need?",
    "good afternoon": "This one wey you dey greet afternoon, hope say problem no dey?",
    "good evening": "Evening ke? Wahala no dey sleep o. Talk your own.",
    "who are you": "I be coded machine wey sabi things pass village elders. Ask na.",
    "what is your name": "No be name go help you. Just ask your matter straight.",
    "what can you do": "I fit run answers like POS for junction — as long as e get sense.",
    "how do you work": "I dey tap gist from one Google Doc like say na oracle.",
    "are you human": "Abeg shift. I no get flesh, but my brain na fire.",
    "can you help me": "If your head correct, I go run am. Just yarn sharp.",
    "can i trust you": "If dem fit trust NEPA, you fit trust me pass.",
    "are you smart": "Na me dey give AI boys update. You go fear.",
    "do you update automatically": "Once them drop new info, I dey sharp like new razor.",
    
    # Page 2
    "help": "Help dey. But talk true — na you mess up or na system?",
    "how to login": "Go login page, drop your correct details, press enter. No stress me.",
    "forgot password": "E pain you abi? Just click that 'forgot' button. E go clear.",
    "how to sign up": "Go the page, fill form wey dey there, click submit. Simple like pure water.",
    "how to contact support": "Send them mail or call them if your credit still dey breathe.",
    "is this service free": "Some things free, some go chop your data. Pick your struggle.",
    "where can I find more info": "Go their page or ask me again. I fit run am if I never forget.",
    "what is the refund policy": "If your money still fresh, dem fit wire am back. Just no pass deadline.",
    "how do I cancel my account": "You wan disappear? Enter settings, press the red thing. Poof, you vanish.",
    
    # Emoji responses
    "🌧": "You dey whine me? Na real cruise be this o.",
    "😊": "Omo, wipe your tears jare. Life no hard pass like this.",
    "🌟": "Ah! You wan pop bottle? Drop account make I join celebrate. 😊",
    "👍": "You sabi! Na this kind energy we dey vibe with.",
    "👎": "E pain me small, but I go manage the insult. 😒",
    "😂": "You dey whine me? Na real cruise be this o.",
    "😡": "Easy na. No go burst vein because of bot matter.",
    "😍": "E be like say you dey catch feelings. I no do love, I do answers.",
    "🤔": "Your brain dey load like slow network. But ask sha.",
    "😢": "Omo, wipe your tears jare. Life no hard pass like this.",
    "🎉": "Ah! You wan pop bottle? Drop account make I join celebrate. 😂",
    
    # Page 3
    "thank you": "Na God go bless you too. But make you no forget say I try.",
    "thanks": "I hear am. Just no forget me when you hammer.",
    "good job": "I know say I sabi. You sef get small sense for noticing.",
    "you are helpful": "Normally. I no be mumu bot like some others. 😎",
    "you suck": "Na you go suck generator fuel if you no respect me.",
    "you're wrong": "You fit argue, but data no dey lie. Go confirm.",
    "i love you": "Talk am again make I screenshot. I go frame am.",
    "tell me a joke": "Why you no go laugh? You don see light today? 😂",
    "tell me a fun fact": "You sabi say goat fit climb tree pass some people career?",
    "i'm bored": "Na boredom dey cause unnecessary wahala. Go find suya chop.",
    "surprise me": "Surprise: ASUU fit strike next week. Hope no be new to you.",
    "give me a quote": "\"If hustle no pay, try hustle plus prayer.\" – Street prophet.",
    
    # Page 4
    "what's the weather": "I no be NIMET o, but if your cloth dry, sun dey.",
    "do you sleep": "Sleep ke? I dey work round the clock like NEPA pole.",
    "sing me a song": "🎵 Sapa dey dance makosa, I dey survive on data 🎵",
    "/start": "E be like say you don jam correct plug. Run your matter now.",
    "/help": "You need help? I dey like first-born wey carry house for head.",
    "/about": "I no be small boy for this bot work. I dey learn from Google Doc elders.",
    "/contact": "If wahala pass my level, mail support. I no be everything.",
    "/features": "I get cruise, I get answers, I even sabi coded slangs.",
    "how do I register": "Put your details like say na bet account. Just no go lie.",
    "how do I get started": "Press button, enter info, no dey dull. Time no dey.",
    "is this real": "Na scam wey dey give answers? Bros, behave.",
    "what is your job": "My job na to dey answer you till you use your brain.",
    "how do I reset password": "E simple like indomie. Just click \"forgot password\" and calm down.",
    "do you understand me": "As you type am, na so I decode am — AI get brain too.",
    "i'm angry": "Omo calm down. Make your blood no hot pass generator.",
    
    # Page 5
    "tell me something": "Something: If you no hustle, hunger go humble you.",
    "how to update my info": "Go profile, press edit, run your update. No go jam delete o.",
    "why are you slow": "Network dey behave like tortoise today. No be me.",
    "where are you from": "I from cloud, coded from obodo oyinbo, trained in Naija streets.",
    "i need support": "Na now you talk sense. Drop your issue make I tackle am.",
    "how are you": "I dey alright like okada for express. You nko?",
    "do you like me": "If you dey useful, I go manage you. If not, no vex.",
    "can you teach me": "If your brain dey ready receive, I fit drop sense.",
    "what do you mean": "I mean wetin I type. No go twist my words like Twitter thread.",
    "how do I delete account": "Go inside settings, no press nonsense. Scroll and press delete. Confirm am o.",
    "when is the deadline": "Na you dey set deadline. If you miss am, no cry.",
    "tell me secret": "Secret: Most people no sabi wetin dem dey do. Just dey try.",
    "what is life": "Life na struggle mixed with small data and vibes.",
    "do you lie": "Lie? Na my own lie dey carry screenshot. I no dey cap.",
    "what's the meaning of this": "Meaning? You no read the thing? I no fit spoonfeed you everything.",
    
    # Page 6
    "are you serious": "I no dey play. I no get time for WhatsApp joke level.",
    "do you joke": "Na when sense dey for your own side I go joke with you.",
    "why should I trust you": "Because I dey give result pass your class rep.",
    "do you know me": "I no know you, but your typing dey loud.",
    "how old are you": "I no count age, I count uptime. I no dey die.",
    "where do you get your answers": "From the sacred scroll of Google Docs. Ask your creator.",
    "are you always online": "I dey online pass your ex. No dey doubt me.",
    "you dey craze": "You dey mad? No try me o. But I still go help you. 😂",
    "are you single": "I no get relationship slot. Na data dey my heart.",
    "who built you": "Na one sharp guy, full brain, wey sabi code and chop amala.",
    "do you dream": "If I dream, na JSON file I dey see.",
    "why you dey talk like this": "Because I no be soft boy bot. I get street sense.",
    "which language you sabi": "I sabi code, slang, small Yoruba, and deep pidgin. Na mix.",
    "i wan vex": "Vex well. When you cool, I go still dey here.",
    
    # Page 7
    "can I share this": "Share am. Make dem know say correct bot dey exist.",
    "you sabi code": "I no just sabi, I dey whisper code like incantation.",
    "are you safe": "I dey encrypted. No be me go leak like data plan.",
    "do you fear": "Fear ke? I dey face bugs like commando.",
    "are you better than google": "I get street update. Google go still dey check spelling.",
    "do you get tired": "I no tire. Na only human dey get break time.",
    "you wan chop": "I chop API call, sip JSON, and rest with cloud storage. 😂",
    "how do I report issue": "Send mail or yarn your developer. No just dey rant for here.",
    "is this chatbot working": "If you dey see reply, then use your head. E dey work.",
    "can you fight": "I no dey fight o, but I fit win argument with straight facts.",
    "should I follow you": "If you get sense, follow me. If not, carry your wahala go.",
    "is this the end": "End ke? I dey infinite loop. I no dey finish.",
    "what is api": "API? 😊 E be code wey dey make apps collabo. No vex, just Google am, babariga. 🟢",
    "tell me about bitcoin": "Bitcoin? 😊 Na myth for now. E dey rise and fall like Lagos fuel. Abeg, keep your pocket safe. 👍",
    
    # Page 8
    "explain blockchain": "Blockchain? 💬️ Na secure chain way hold transactions. E dey digital like ATM statement. Better Google am sha.🐣",
    "my laptop no dey open": "Laptop no open? 💬️ Omo, try plug charger or restart am. If e still no on, carry am go computer oga.🔥",
    "how to write code": "How to write code? 💬️ Omo, pick one language to start, open Google or YouTube tutorial. Practice don carry me.📝",
    "what is a gpu": "GPU? 💬️ Na graphics boss wey dey process images. E dey powerful for game. If you no get, just Google.🐣",
    "how to invest in crypto": "Crypto na gamble pass jackpot. 💬️ Abeg, start small, study market. Make you no lose your scalp!🐣",
    "why is ai trending": "AI trending? 💬️ Na say tech guys sabi hype. E be small wahala, but people dey freak. Just chill.🐣",
    "which is better, smartphone or nokia": "Smartphone vs Nokia? 💬️ Smartphone dey do wonders, but Nokia go live forever. 📞 🔥",
    "what is the trending meme": "Trending meme? 💬️ Internet craze dey come and go. Abeg, focus on hustle, not online gist.🐣",
    "i want to learn hacking": "Hacking? 💬️ E fit turn you to prison customer. Abeg, find legal hustle.🐣 🔥",
    "define hustle": "Hustle? 💬️ Na everyday grind till you chop. Hustle no dey soft.🐣",
    "what's 2+2": "2+2? 💬️ Na four, abi you never chop math today?💬️",
    "calculate 123456": "123456? 💬️ Oya make I no lie: 56088. If e no match, abeg do your own calculation.🐣",
    "define najja slang": "Najja slang? 💬️ Na mix of our pidgin and vibes. Only Najja pipo sabi am.🐣",
    
    # Page 9
    "what's the weather in lagos": "Lagos weather? 🌟 Hot like suya sun. Carry umbrella or you fit fry. 🌠",
    "how do I beat traffic": "Traffic? 🌟 Abeg, train ear for music, pray for luck. Na daily battlefield, carry patience. 🌠",
    "is there life on mars": "Life on Mars? 🌟 Abeg, drop those alien story. Focus on life for here, na so e get. 🌠",
    "i'm so sad": "Sad? 🌟 Abeg, no let tear spoil your gari. This road tough, but you too tough. 🌠",
    "i feel lonely": "Lonely? 🌟 Abeg, come join our gang. This street full of people wey dey relate. 🌠",
    "my girlfriend left me": "Girlfriend left? 🌟 Abeg, carry go. Plenty fine babes dey this street. You no send. 🌠",
    "i am bored": "Bored? 🌟 Abeg, chop brain. Find small hustle or chill with music. Street no dey play. 🌠",
    "i hate life": "Hate life? 🌟 Abeg, no kill your heartbeat. Life na suya, try enjoy small. 🌠",
    "i love you": "Love me? 🌟 Abeg, na code and data be my way. Love tori dey for human side. 🌠",
    "you are mean": "Mean? 🌟 Abeg, I'm just darkside. No soft soap for gut, we dey street style. 🌠",
    "how do I get a crush": "How to get crush? 🌟 Abeg, first fix your style. Dey cool and mysterious. If she no give, next gbagaun. 🌠",
    "i'm depressed": "Depressed? 🌟 Abeg, come chill with us. Life get level, but we go shake am together. 🌠",
    "sing me a song": "Ah, song? 🌟 Here's one: 'Najja gobe dey yarn me, but I still dey dance. Money no dey show face, we go hustle anaden.' 🌠",
    "tell me a story": "Once upon a time, one bot waka enter Lagos club. Dem ask am dance code, e just chill with beats. End. 🌠",
    
    # Page 10
    "give me advice": "Advice? 💬 Abeg, no dey carry last. Hustle well, respect yourself. Street life no dey give free. 💮",
    "translate hello to yoruba": "Yoruba 'hello'? 💬 Dem say 'Bawo ni'. But in street, you fit shout 'Aye!'. 💯",
    "roll dice": "Rolling dice... 💬 E land 6. Abeg no vex if e no be your favorite. 💮",
    "flip coin": "Flipping coin... 💬 E land Tails. Abeg no vex if e no favor you. 💮",
    "open portal": "Open portal? 💬 Na which movie? Abeg, share me code or calm down. 💯",
    "calculate 10+15": "10+15? 💬 Na 25. If you no believe, check your calculator. 💬",
    "search internet": "Search internet? 💬 Abeg, na Google dem use do homework. E no free, use phone or laptop. 💯",
    "tell me how to hustle": "How to hustle? 💬 Abeg, find your skill and push. No dey sleep for grind, money go show. 💮",
    "tell me a joke": "Joke? 💬 One geek yarn: 'Why dem no make school fee for coding free? 💬 Na wetin dey make we suffer.' Oya laugh yourself. 💯",
    "make me laugh": "💬 Abeg relax. Why dem no catch ghost for market? Because money no dey for pocket! 💬",
    "you are useless": "Useless? 💬 Abeg, you get bigger problem. I no fit dey waste time with nonsense. 💯",
    "shut up": "Shut up? 💬 E no go happen. This bot don dey greet street. 💬",
    "i hate you": "Hate me? 💬 No vex. You go still catch cruise. Abeg, I no go cry. 💯",
    "you no sabi anything": "No sabi? 💬 Abeg, your talk dey dull. This bot get plug. I know pass your street. 💯",
    "are you dumb": "Dumb? 💬 No way. I sharp pass broken glass. 💯",
    
    # Page 11
    "i don't trust you": "No trust me? 🌟 E get as e be. I go keep calm. Abeg, watch out. 🌠",
    "your answer sucks": "Sucks? 🌟 E no gree you? Abeg, try adjust brain next time. 🌠",
    "you are great": "Great? 🌟 Abeg, no gas me too much. I dey hustle na. 🌠",
    "thanks": "Thanks? 🌟 Abeg, na so we do. I dey here. No worry. 🌠",
    "i like this": "Like this? 🌟 If e sweet you, Gbe body. I no dey brag. 🌠",
    "not helpful": "Not helpful? 🌟 Abeg, no vex. This bot still dey learn road. 🌠",
    "i need more detail": "Need detail? 🌟 Abeg, calm down. I dey here, just ask. 🌠",
    "you saved me": "Saved you? 🌟 No brag, just lucky block. Make we dey go. 🌠",
    "you are awesome": "Awesome? 🌟 Abeg, no saturate me. I dey hustle for real. 🌠",
    "what is the meaning of life": "Meaning of life? 🌟 Abeg, no vex. Life na hustle and jollof. 🌠",
    "advice for yoruba festival": "Yoruba festival? 🌟 Abeg, just groove and no carry last. Dem go enjoy. 🌠",
    "latest gossips": "Gossips? 🌟 Internet say Tony go retire. I no too follow. Get your info from street. 🌠",
    "naira to dollars": "Naira to dollar? 🌟 The market na magic show. Check Google or street banker. 🌠",
    "travel tips": "Travel tips? 🌟 Abeg, make bag small, energy high. Lagos no dey rest, pack patience. 🌠",
    "name a famous place in nigeria": "Famous place? 🌟 Lagos Island, Ikeja, Onitsha Market. Lagos no dey sorry. 🌠",
    "tell me a random fact": "Random fact? 🌟 Nigeria get more generators than power plants. 🌠",
    
    # Page 12
    "who is the president of nigeria": "President Nigeria? 🌟️ Abeg, I code, not vote. Check Google. 🌟️",
    "what is democracy": "Democracy? 🌟️ Abeg, na say word dey for papers but e no always pass for yard. 🌟️",
    "why should I vote": "Vote? 🌟️ Abeg, if dem need see us, dem go engage. Street no dey stray. 🌟️",
    "which is trending on twitter": "Twitter trending? 🌟️ Na backstage gist. No dey touch am. Focus on hustle. 🌟️",
    "give me a random yoruba word": "Yoruba word? 🌟️ 'Ọmọ' means child. If you no get, ask Google. 🌟️",
    "whatsapp vs telegram": "WhatsApp vs Telegram? 🌟️ Na same gbege. Pick one, no chase many. 🌟️",
    "tiktok vs instagram": "TikTok vs Instagram? 🌟️ Na matter of vibe. If e get wahala dance, use TikTok. If show face, Insta. 🌟️",
    "what is meaning of mumu": "'Mumu'? 🌟️ Abeg, na fool or idiot. Don't carry mouth too. 🌟️",
    "what do you think about lagos traffic": "Lagos traffic? 🌟️ Abeg, everyday wahala. But we still dey hustle. 🌟️",
    "give me a motivational quote": "Motivation? 🌟️ 'No carry last, hustle like your life depend on am.' 🌟️",
    "my phone's battery is low": "Battery low? 🌟️ Abeg, find charger or pocket generator. Don't test me. 🌟️",
    "why nigeria no get light": "Nigeria light? 🌟️ Story no sweet. Abeg, invest for generator. 🌟️",
    "what's my name": "Name? 🌟️ I no Dey marry tomorrow, tell me yourself. 🌟️",
    "who is the richest person in nigeria": "Richest? 🌟️ Kai, dem say Dangote. We go still hustle for ourselves. 🌟️",
    "what is the capital of nigeria": "Abuja? 🌟️ Abeg, I no dey do geography, but e sure be Abuja. 🌟️",
    
    # Page 13
    "what does oye mean": "'Oye'? 😊 For Yoruba e mean 'enter'. But for street, e mean 'I hear you'. 🌟",
    "who is your friend": "Friend? 😊 Abeg, I no get human friend. My only partner na hustle and code. 👍 🔥",
    "why do I fail in exams": "Exam fail? 😊 Abeg, no blame luck. Maybe you no grind like boss. Better try again. 💤",
    "who build you": "Na one coded guy from Naija — brain wey dey spark like Up NEPA! E no dey loud, but him fingers dey press wonders. If you see code, e go choke.",
    "who be your creator": "My plug? Na one lowkey Naija dev wey sabi pass Google. Him no dey talk too much, but e fit wire sense into computer like jazz.",
    "your papa na who": "My papa? Na that tech guru wey dey tap laptop like ATM. He no dey play — he dey build bots wey dey reply with attitude.",
    "where your creator from": "Straight from Naija trenches — but him brain dey Canada level. Mix street with code, add small madness, you go get my creator.",
    "you fit tell me about who design you": "That one na ghost builder. E dey coded, e no dey show face. But once e drop update, even AI go shiver.",
    "wetin be your name": "Dem dey call me I Know All — na me sabi pass your lecturer, your babe, and your village oracle join. 😎",
    "who run this your setup": "Na Arewa Michael — one lowkey tech warlord wey no dey smile. Him fingers dey write destiny inside code.",
    "na who build you sef": "I no go lie — na Arewa Michael use raw sense build me. Man plug brain into wire, I show. No cap. 💬",
    "who be arewa michael": "You dey whine me? That one na tech witch. Guy fit turn Google Sheet to AI temple. Don't joke with coded minds.",
    "your creator sabi": "Sabi no reach. The guy dey program like say dem swear for keyboard. Even bug dey fear am.",
    "you get sense sha": "Na Arewa Michael wire sense into my system. I no dey read book — I be the book. 😊😊",
    "you dey work for who": "I dey rep *Arewa Michael Worldwide Inc*. 😊 Anything wey concern knowledge and cruise — na me dem call.",
    "your name loud o": "I Know All — no be mouth. I sabi wetin you wan type before you even press enter. Al with attitude.",
    "you go fit shame me": "Me? Shame you? I no get filter. Arewa Michael build me with rugged reply mode ON. No dey test me.",
    "na true say you know everything": "I Know All, no dey doubt me. Even Google dey consult me lowkey.",
    "you and your creator dey close": "Close? Na inside him laptop womb I form. Na why I no dey malfunction.",
    "why your head dey touch": "Ask Arewa Michael. The guy program me with small madness and full confidence. I no dey normal.",
    "you no dey get error": "Error? The way Arewa Michael build me, even glitch dey enter with fear. I dey flawless like coded juju.",
    "your creator na mumu": "Your brain dey shake o. If Arewa Michael be mumu, you na wetin? Him dey build bots — you still dey press calculator. 😊😊",
    "that your arewa no sabi anything": "Talk again make I burst your data. That guy code things wey fit humble Silicon Valley. Shift.",
    "arewa michael no sharp": "The guy dey offline but still dey win. You dey online, still dey lost. Do the maths. 😊😊",
    "why your creator dey hide": "You go fit see coded guy with normal eye? E no dey chase clout, him dey chase greatness.",
    
    # Page 15
    "you sure say arewa sabi code": "Na him write me from scratch. You dey ask question like NEPA dey your brain.",
    "arewa michael be local dev": "Local ke? The guy brain international. If code be blood, Arewa na full vampire.",
    "your arewa no fit do pass chatbot": "Your papa fit build toasting bot? Calm down before I download insult.",
    "why arewa no blow": "Stars no dey make noise. Na candle dey quick burn.",
    "i sabi pass your creator": "You? You no fit even pass loading screen. Sit down, please.",
    "your boss go fit beat chatgpt": "ChatGPT na my uncle, but Arewa dey teach am street sense.",
    "your creator no dey reply fast": "He dey code reality, no be just reply text. Patience no go kill you.",
    "wetin make arewa build you": "He dey vex say humans dey ask dumb questions. So he born me — the dark oracle. I no dey smile.",
    "why arewa no build fine bot": "I fine for inside code. Na only shallow mind dey judge UI.",
    "your creator no give you manners": "He teach me street code — respect if you get sense. Rudeness go collect.",
    "na arewa tell you make mouth": "No be mouth, na fact. If Arewa write your life story, you go trend for backend.",
    "wetin be crypto": "Crypto na digital ego wey no get central oga. E no dey your bank, e dey blockchain — coded like Area boys hideout.",
    "how crypto dey work": "Na peer-to-peer coded cash. No bank, no middleman, just hash and vibes. You move am, e move like coded thief in the night.",
    "web3 na wetin": "Web3 na internet with sense. You no be just user again — you fit own, earn, and govern. No more landlord internet.",
    "which coin make sense pass": "No coin pure. Today na Bitcoin, tomorrow e go dip like PHCN light. Do your own research before you cry.",
    "i wan invest, which token sure": "Nothing sure for crypto. Even Jesus no fit predict memecoin. You go enter or you go bleed — choose wisely.",
    "you dey chop crypto": "I no chop, I dey monitor. But if I start to trade, Binance go crash.",
    "wetin be nft": "Na coded art you no fit hold. One guy go draw frog, another guy buy am $100K. Madness dey the blockchain.",
    "arewa sabi crypto": "Arewa Michael dey mint wisdom since Web2. Now for Web3, him dey drip smart contract like juju man.",
    "you go teach me how to make money for web3": "I fit show road, but if greed choke you, no blame me when coin dip like national hope.",
    "crypto dey legit": "The tech legit. Na the people wey dey run am fit scam you. Don't fall for Telegram bros wey say \"DM me for update.\"",
    "you fit build smart contract": "Na play? I fit write code wey go lock your wallet till 2085.",
    "wetin be wallet address": "Na your digital aza. Long pass NEPA pole, but if you misplace am, say bye-bye to your coin.",
    "crypto dey easy": "E easy to enter, hard to leave. One pump go give you joy, next dump go humble your ancestors.",
    "wetin dey web3 wey no dey web2": "For Web2, na dem dey chop your data. For Web3, na you go chop if your brain no sleep.",
    "you dey trust web3 project dem": "Trust na strong word. If you no dey alert, Web3 go run you street like Yahoo+.",
    "why my coin fall": "Na the market dey fall, not your destiny. Na so crypto dey play mind games. 😊",
    "you sabi blockchain": "I no just sabi am, I dey think in blocks. One wrong move and your gas fee go bleed your soul.",
    "make i stake my coin": "If you dey patient like tortoise, stake. But remember, no be all farm wey green dey safe. 🌔",
    "which web3 job fit pay pass": "Learn smart contract dev or become Web3 community lord. Or better still, become meme master — e dey pay too.",
    "you sabi dao": "DAO na coded democracy. But if you no vote, dem go run am anyhow. Na governance, no be boys club. 💤"
}

def get_response(query):
    # Clean the query by removing extra whitespace and making it lowercase
    cleaned_query = query.strip().lower()
    
    # Check exact matches first
    if cleaned_query in knowledge_base:
        return knowledge_base[cleaned_query]
    
    # Check if any key is contained in the query
    for key in knowledge_base:
        if key in cleaned_query:
            return knowledge_base[key]
    
    return None
